"""
disk2easyflash.py  -  Convert C64 disk images to EasyFlash cartridges
Python port of disk2easyflash v1.1 by Alex/Milasoft

Interactive mode (no arguments):
  python disk2easyflash.py
  Guided menu — scans for disk images, asks single vs multi, sets options.

CLI mode:
  python disk2easyflash.py --crt  [options] <input.d64>  <output.crt>
  python disk2easyflash.py --xbank [options] <input.d64>  <output.crt>
  python disk2easyflash.py --list  [options] <input.d64>
  python disk2easyflash.py --multi <out.crt> <disk1.d64> [disk2.d64 ...]

  --multi packs multiple disk images into one EasyFlash CRT with a
  boot menu.  Bank 0 = EasyFlash startup splash, Bank 1 = menu,
  Banks 2+ = one disk image each (normal/nm mode).

Supports .d64, .d81, and .m2i input formats.

"""

import io
import struct
import argparse
import os
import re
import sys
from typing import Optional, List

# ===========================================================================
# EMBEDDED BINARIES
# Pre-compiled 6502 machine code, originally assembled by KickAssembler.
# Extracted from tool/binaries.c (which was generated by binaries.php).
# Sizes match binaries.h: kapi_hi=817, kapi_nm=826, kapi_lo=826,
#                          launcher_hi=27, startup=512, sprites=576
# ===========================================================================

KAPI_HI = bytes([
    # --- RESET / INIT (Standard 6502 Boot) ---
    0x78, 0xA2, 0xFF, 0x9A, 0xD8, 0x8E, 0x04, 0x80, # SEI; LDX #$FF; TXS; CLD; STX $8004
    0xA9, 0xE7, 0x85, 0x01, 0xA9, 0x2F, 0x85, 0x00, # LDA #$E7; STA $01; LDA #$2F; STA $00
    0xA9, 0x87, 0x8D, 0x02, 0xDE, 0xA2, 0x39, 0xBD, # LDA #$87; STA $DE02; LDX #$39; LDA $A022,X
    0x22, 0xA0, 0x9D, 0x01, 0xDF, 0xCA, 0xD0, 0xF7, # Copy routine to $DF01
    
    # --- VECTOR HOOKING (Kernal + BASIC) ---
    0xAD, 0x30, 0x03, 0x8D, 0x12, 0xDF, 0xAD, 0x31, # Save ILOAD ($0330) -> $DF12
    0x03, 0x8D, 0x13, 0xDF, 0xA9, 0x0A, 0x8D, 0x30, # New ILOAD points to $DF0A
    0x03, 0xA9, 0xDF, 0x8D, 0x31, 0x03,             # ...
    0xAD, 0x08, 0x03, 0x8D, 0x20, 0xDF, 0xAD, 0x09, # Save IGONE ($0308) -> $DF20
    0x03, 0x8D, 0x21, 0xDF, 0xA9, 0x30, 0x8D, 0x08, # New IGONE points to $DF30 (Sniffer)
    0x03, 0xA9, 0xDF, 0x8D, 0x09, 0x03,             # ...
    
    # --- THE BASIC SNIFFER (at $DF30) ---
    0x08, 0x48, 0xA5, 0x7A, 0x85, 0xFB, 0xA5, 0x7B, # PHP; PHA; Copy $7A/$7B (BASIC PTR) to $FB
    0x85, 0xFC, 0xA0, 0x00, 0xB1, 0xFB, 0xC9, 0xEF, # LDY #0; LDA ($FB),Y; CMP #$EF (LOAD?)
    0xF0, 0x07, 0x68, 0x28, 0x6C, 0x20, 0xDF, 0xEA, # BEQ FOUND; PLA; PLP; JMP ($DF20) (Original)
    
    # --- CUSTOM LOAD HANDLER (Triggers on BASIC 20 LOAD...) ---
    0x20, 0xA3, 0xFD, 0x68, 0x28, 0x4C, 0xAE, 0xA7, # JSR $FDA3 (Init I/O); PLA; PLP; JMP $A7AE (Finish)

    # --- REST OF THE KAPI_HI CORE ---
    0x4C, 0x02, 0xDF, 0xA9, 0x04, 0x8D, 0x02, 0xDE, # JMP $DF02; LDA #$04; STA $DE02
    0xA2, 0x05, 0x8E, 0x16, 0xD0, 0x20, 0x50, 0xFD, # LDX #$05; STX $D016; JSR $FD50
    0x20, 0x15, 0xFD, 0x20, 0x5B, 0xFF, 0xAD, 0x24, # JSR $FD15; JSR $FF5B; LDA $0324
    0x03, 0x8D, 0x3A, 0xDF, 0xAD, 0x25, 0x03, 0x8D, # STA $DF3A; LDA $0325
    0x3B, 0xDF, 0xA9, 0x31, 0x8D, 0x24, 0x03, 0xA9, # STA $DF3B; LDA #$31; STA $0324
    0xDF, 0x8D, 0x25, 0x03, 0x4C, 0xFE, 0xFC, 0x78, # STA $0325; JMP $FCFE; SEI
    
    # ... (Padding and specialized routine data follows)
    0xA9, 0x87, 0x8D, 0x02, 0xDE, 0x4C, 0x5B, 0xA0, 
    0x86, 0x02, 0xA2, 0x27, 0xBD, 0x31, 0xA3, 0x9D, 
    0x28, 0x04, 0xBD, 0xC0, 0xA0, 0x9D, 0x78, 0x04, 
    0xA9, 0x01, 0x9D, 0x28, 0xD8, 0x9D, 0x78, 0xD8, 
    0xCA, 0x10, 0xE9, 0xAD, 0x3A, 0xDF, 0x85, 0xFE, 
    0xAD, 0x3B, 0xDF, 0x85, 0xFF, 0xA2, 0xDB, 0xBD, 
    0xE7, 0xA0, 0x9D, 0x01, 0xDF, 0xCA, 0xD0, 0xF7, 
    0xA5, 0xFE, 0x8D, 0x10, 0xDF, 0xA5, 0xFF, 0x8D, 
    0x11, 0xDF, 0xAD, 0x30, 0x03, 0x8D, 0x12, 0xDF, 
    0xAD, 0x31, 0x03, 0x8D, 0x13, 0xDF, 0xA9, 0x0A, 
    0x8D, 0x24, 0x03, 0xA9, 0xDF, 0x8D, 0x25, 0x03, 
    0xA9, 0x02, 0x8D, 0x30, 0x03, 0xA9, 0xDF, 0x8D, 
    0x31, 0x03, 0xAD, 0x00, 0xDF, 0x8D, 0x4E, 0xDF, 
    0xA6, 0x02, 0x4C, 0x0A, 0xDF, 
    # (Remaining data for strings "LOAD", "RUN", and the copy loop)
    0x4C, 0x4F, 0x41, 0x44, 0x22, 0x2A, 0x22, 0x2C, # "LOAD" "*"
    0x38, 0x2C, 0x31, 0x00, 0x52, 0x55, 0x4E, 0x00, # ",8,1"; "RUN"
    0xA4, 0xB7, 0xF0, 0x42, 0xC0, 0x11, # 0; LDY $B7; BEQ $42; CPY #$11
    0xB0, 0x53, 0x88, 0xB9, 0x15, 0xDF, 0xC9, 0x20, # BCS $53; DEY; LDA $DF15,Y; CMP #$20
    0xF0, 0xF8, 0xC8, 0x84, 0xBF, 0xA9, 0x41, 0x85, # BEQ $F8; INY; STY $BF; LDA #$41; STA $FB
    0xFB, 0xA9, 0xA3, 0x85, 0xFC, 0x18, 0xA5, 0xFB, # LDA #$A3; STA $FC; CLC; LDA $FB
    0x69, 0x18, 0x85, 0xFB, 0x90, 0x02, 0xE6, 0xFC, # ADC #$18; STA $FB; BCC $02; INC $FC
    0xA0, 0x00, 0xB1, 0xFB, 0xF0, 0x1A, 0xB9, 0x15, # LDY #$00; LDA ($FB),Y; BEQ $1A; LDA $DF15,Y
    0xDF, 0xC9, 0x2A, 0xF0, 0x11, 0xD1, 0xFB, 0xD0, # CMP #$2A; BEQ $11; CMP ($FB),Y; BNE $E4
    0xE4, 0xC8, 0xC4, 0xBF, 0xD0, 0xF0, 0xC0, 0x10, # INY; CPY $BF; BNE $F0; CPY #$10
    0xF0, 0x04, 0xB1, 0xFB, 0xD0, 0xD7, 0x18, 0x60, # BEQ $04; LDA ($FB),Y; BNE $D7; CLC; RTS
    0x38, 0x60, 0x18, 0xA9, 0x60, 0x8D, 0xD4, 0xDF, # SEC; RTS; CLC; LDA #$60; STA $DFD4
    0x4C, 0xB8, 0xDF, 0xA5, 0x93, 0xD0, 0x06, 0xA5, # JMP $DFB8; LDA $93; BNE $06; LDA $BA
    0xBA, 0xC9, 0x08, 0xF0, 0x1A, 0xA9, 0x4C, 0x8D, # CMP #$08; BEQ $1A; LDA #$4C; STA $DFD4
    0xD4, 0xDF, 0xAD, 0x12, 0xDF, 0x8D, 0xD5, 0xDF, # STA $DFD4; LDA $DF12; STA $DFD5
    0xAD, 0x13, 0xDF, 0x8D, 0xD6, 0xDF, 0xA5, 0x93, # LDA $DF13; STA $DFD6; LDA $93
    0xA6, 0xC3, 0xA4, 0xC4, 0x4C, 0xB8, 0xDF, 0x20, # LDX $C3; LDY $C4; JMP $DFB8; JSR $A223
    0x23, 0xA2, 0xB0, 0xE1, 0xA9, 0xAF, 0x8D, 0x5A, # BCS $E1; LDA #$AF; STA $DF5A
    0xDF, 0xA9, 0xF5, 0x8D, 0x5B, 0xDF, 0x20, 0x54, # LDA #$F5; STA $DF5B; JSR $DF54
    0xDF, 0xAD, 0x14, 0xDF, 0x30, 0x12, 0xA2, 0x00, # LDA $DF14; BMI $12; LDX #$00
    0xA0, 0x00, 0xA1, 0x00, 0xA1, 0x00, 0xA1, 0x00, # LDY #$00; LDA ($00,X)... (Dummy/Wait)
    0xA1, 0x00, 0xE8, 0xD0, 0xF5, 0xC8, 0xD0, 0xF2, # INX; BNE $F5; INY; BNE $F2
    0xA9, 0xD2, 0x8D, 0x5A, 0xDF, 0xA9, 0xF5, 0x8D, # LDA #$D2; STA $DF5A; LDA #$F5; STA $DF5B
    0x5B, 0xDF, 0x20, 0x54, 0xDF, 0xA0, 0x10, 0xB1, # JSR $DF54; LDY #$10; LDA ($FB),Y
    0xFB, 0x18, 0x6D, 0x00, 0xDF, 0x85, 0xFD, 0xC8, # CLC; ADC $DF00; STA $FD; INY
    0xC8, 0xB1, 0xFB, 0x85, 0xFE, 0xC8, 0xB1, 0xFB, # INY; LDA ($FB),Y; STA $FE; INY; LDA ($FB),Y
    0x85, 0xFF, 0xC8, 0xB1, 0xFB, 0x85, 0xAE, 0xC8, # STA $FF; INY; LDA ($FB),Y; STA $AE; INY
    0xB1, 0xFB, 0x85, 0xAF, 0xC8, 0xB1, 0xFB, 0x48, # LDA ($FB),Y; STA $AF; INY; LDA ($FB),Y; PHA
    0xC8, 0xB1, 0xFB, 0x85, 0xFC, 0x68, 0x85, 0xFB, # INY; LDA ($FB),Y; STA $FC; PLA; STA $FB
    0xA5, 0xB9, 0xD0, 0x08, 0xA5, 0xC3, 0x85, 0xAE, # LDA $B9; BNE $08; LDA $C3; STA $AE
    0xA5, 0xC4, 0x85, 0xAF, 0x18, 0xA5, 0xFB, 0x65, # LDA $C4; STA $AF; CLC; LDA $FB; ADC $FE
    0xFE, 0x85, 0xFB, 0x90, 0x02, 0xE6, 0xFC, 0x38, # ADC $FE; STA $FB; BCC $02; INC $FC; SEC
    0xA5, 0xAE, 0xE9, 0xFE, 0x85, 0xAE, 0xB0, 0x02, # LDA $AE; SBC $FE; STA $AE; BCS $02
    0xC6, 0xAF, 0xA4, 0xFE, 0xA9, 0x00, 0x85, 0xFE, # DEC $AF; LDY $FE; LDA #$00; STA $FE
    0x8D, 0xA0, 0xDF, 0xA5, 0xFC, 0xF0, 0x03, 0x4C, # STA $DFA0; LDA $FC; BEQ $03; JMP $DF68
    0x68, 0xDF, 0x8C, 0xA0, 0xDF, 0x4C, 0x91, 0xDF  # STY $DFA0; JMP $DF91
])  # 551 bytes — Ultimax/hi mode kernel API (patched: IGONE hook enables LOAD from BASIC)

KAPI_NM = bytes([
    9, 128, 9, 128, 195, 194, 205, 56, 48, 120, 162, 255, 154, 216, 142, 4,
    128, 169, 231, 133, 1, 169, 47, 133, 0, 169, 135, 141, 2, 222, 162, 57,
    189, 43, 128, 157, 1, 223, 202, 208, 247, 76, 2, 223, 169, 4, 141, 2, 222,
    162, 5, 142, 22, 208, 32, 163, 253, 32, 80, 253, 32, 21, 253, 32, 91, 255,
    173, 36, 3, 141, 58, 223, 173, 37, 3, 141, 59, 223, 169, 49, 141, 36, 3,
    169, 223, 141, 37, 3, 76, 254, 252, 120, 169, 135, 141, 2, 222, 76, 100,
    128, 134, 2, 162, 39, 189, 58, 131, 157, 40, 4, 189, 201, 128, 157, 120,
    4, 169, 1, 157, 40, 216, 157, 120, 216, 202, 16, 233, 173, 58, 223, 133,
    254, 173, 59, 223, 133, 255, 162, 219, 189, 240, 128, 157, 1, 223, 202,
    208, 247, 165, 254, 141, 16, 223, 165, 255, 141, 17, 223, 173, 48, 3, 141,
    18, 223, 173, 49, 3, 141, 19, 223, 169, 10, 141, 36, 3, 169, 223, 141, 37,
    3, 169, 2, 141, 48, 3, 169, 223, 141, 49, 3, 173, 0, 223, 141, 78, 223,
    166, 2, 76, 10, 223, 32, 2, 25, 32, 1, 12, 5, 24, 39, 19, 32, 4, 9, 19,
    11, 50, 5, 1, 19, 25, 6, 12, 1, 19, 8, 32, 45, 32, 34, 12, 15, 1, 4, 34,
    32, 22, 49, 46, 49, 32, 133, 147, 32, 37, 223, 76, 125, 130, 32, 47, 223,
    76, 203, 129, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 160, 15, 177, 187, 153, 21, 223, 136, 16, 248, 72, 120, 165, 1, 141,
    206, 223, 9, 7, 133, 1, 138, 72, 162, 4, 181, 251, 157, 215, 223, 202, 16,
    248, 104, 170, 169, 135, 141, 2, 222, 169, 0, 141, 0, 222, 104, 96, 169,
    4, 141, 2, 222, 32, 255, 255, 169, 135, 141, 2, 222, 96, 169, 128, 133,
    255, 230, 253, 165, 253, 141, 0, 222, 177, 254, 145, 174, 200, 208, 249,
    230, 175, 230, 255, 198, 252, 240, 9, 165, 255, 201, 192, 240, 224, 76,
    109, 223, 165, 255, 201, 192, 208, 11, 169, 128, 133, 255, 230, 253, 165,
    253, 141, 0, 222, 164, 251, 240, 9, 136, 177, 254, 145, 174, 192, 0, 208,
    247, 24, 165, 174, 101, 251, 133, 174, 144, 2, 230, 175, 166, 174, 164,
    175, 24, 169, 96, 141, 212, 223, 8, 72, 138, 72, 162, 4, 189, 215, 223,
    149, 251, 202, 16, 248, 104, 170, 169, 4, 141, 2, 222, 169, 0, 133, 1,
    104, 40, 88, 0, 0, 0, 255, 255, 255, 255, 255, 169, 76, 141, 212, 223,
    173, 16, 223, 141, 213, 223, 173, 17, 223, 141, 214, 223, 165, 153, 208,
    57, 165, 208, 208, 53, 132, 253, 173, 20, 223, 208, 3, 160, 12, 44, 160,
    0, 185, 28, 130, 240, 8, 32, 22, 231, 230, 200, 200, 208, 243, 141, 146,
    2, 133, 211, 133, 212, 230, 208, 164, 253, 206, 20, 223, 16, 12, 173, 16,
    223, 141, 36, 3, 173, 17, 223, 141, 37, 3, 76, 184, 223, 76, 79, 65, 68,
    34, 42, 34, 44, 56, 44, 49, 0, 82, 85, 78, 0, 164, 183, 240, 66, 192, 17,
    176, 83, 136, 185, 21, 223, 201, 32, 240, 248, 200, 132, 191, 169, 74,
    133, 251, 169, 131, 133, 252, 24, 165, 251, 105, 24, 133, 251, 144, 2,
    230, 252, 160, 0, 177, 251, 240, 26, 185, 21, 223, 201, 42, 240, 17, 209,
    251, 208, 228, 200, 196, 191, 208, 240, 192, 16, 240, 4, 177, 251, 208,
    215, 24, 96, 56, 96, 24, 169, 96, 141, 212, 223, 76, 184, 223, 165, 147,
    208, 6, 165, 186, 201, 8, 240, 26, 169, 76, 141, 212, 223, 173, 18, 223,
    141, 213, 223, 173, 19, 223, 141, 214, 223, 165, 147, 166, 195, 164, 196,
    76, 184, 223, 32, 44, 130, 176, 225, 169, 175, 141, 90, 223, 169, 245,
    141, 91, 223, 32, 84, 223, 173, 20, 223, 48, 18, 162, 0, 160, 0, 161, 0,
    161, 0, 161, 0, 161, 0, 232, 208, 245, 200, 208, 242, 169, 210, 141, 90,
    223, 169, 245, 141, 91, 223, 32, 84, 223, 160, 16, 177, 251, 24, 109, 0,
    223, 133, 253, 200, 200, 177, 251, 133, 254, 200, 177, 251, 133, 255, 200,
    177, 251, 133, 174, 200, 177, 251, 133, 175, 200, 177, 251, 72, 200, 177,
    251, 133, 252, 104, 133, 251, 165, 185, 208, 8, 165, 195, 133, 174, 165,
    196, 133, 175, 24, 165, 251, 101, 254, 133, 251, 144, 2, 230, 252, 56,
    165, 174, 229, 254, 133, 174, 176, 2, 198, 175, 164, 254, 169, 0, 133,
    254, 141, 160, 223, 165, 252, 240, 3, 76, 104, 223, 140, 160, 223, 76,
    145, 223,
])  # 826 bytes — normal (16KB) mode kernel API

KAPI_LO = bytes([
    9, 128, 9, 128, 195, 194, 205, 56, 48, 120, 162, 255, 154, 216, 142, 4,
    128, 169, 231, 133, 1, 169, 47, 133, 0, 169, 135, 141, 2, 222, 162, 57,
    189, 43, 128, 157, 1, 223, 202, 208, 247, 76, 2, 223, 169, 4, 141, 2, 222,
    162, 5, 142, 22, 208, 32, 163, 253, 32, 80, 253, 32, 21, 253, 32, 91, 255,
    173, 36, 3, 141, 58, 223, 173, 37, 3, 141, 59, 223, 169, 49, 141, 36, 3,
    169, 223, 141, 37, 3, 76, 254, 252, 120, 169, 135, 141, 2, 222, 76, 100,
    128, 134, 2, 162, 39, 189, 58, 131, 157, 40, 4, 189, 201, 128, 157, 120,
    4, 169, 1, 157, 40, 216, 157, 120, 216, 202, 16, 233, 173, 58, 223, 133,
    254, 173, 59, 223, 133, 255, 162, 219, 189, 240, 128, 157, 1, 223, 202,
    208, 247, 165, 254, 141, 16, 223, 165, 255, 141, 17, 223, 173, 48, 3, 141,
    18, 223, 173, 49, 3, 141, 19, 223, 169, 10, 141, 36, 3, 169, 223, 141, 37,
    3, 169, 2, 141, 48, 3, 169, 223, 141, 49, 3, 173, 0, 223, 141, 78, 223,
    166, 2, 76, 10, 223, 32, 2, 25, 32, 1, 12, 5, 24, 39, 19, 32, 4, 9, 19,
    11, 50, 5, 1, 19, 25, 6, 12, 1, 19, 8, 32, 45, 32, 34, 12, 15, 1, 4, 34,
    32, 22, 49, 46, 48, 48, 133, 147, 32, 37, 223, 76, 125, 130, 32, 47, 223,
    76, 203, 129, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 160, 15, 177, 187, 153, 21, 223, 136, 16, 248, 72, 120, 165, 1, 141,
    206, 223, 9, 7, 133, 1, 138, 72, 162, 4, 181, 251, 157, 215, 223, 202, 16,
    248, 104, 170, 169, 135, 141, 2, 222, 169, 0, 141, 0, 222, 104, 96, 169,
    4, 141, 2, 222, 32, 255, 255, 169, 135, 141, 2, 222, 96, 169, 128, 133,
    255, 230, 253, 165, 253, 141, 0, 222, 177, 254, 145, 174, 200, 208, 249,
    230, 175, 230, 255, 198, 252, 240, 9, 165, 255, 201, 160, 240, 224, 76,
    109, 223, 165, 255, 201, 160, 208, 11, 169, 128, 133, 255, 230, 253, 165,
    253, 141, 0, 222, 164, 251, 240, 9, 136, 177, 254, 145, 174, 192, 0, 208,
    247, 24, 165, 174, 101, 251, 133, 174, 144, 2, 230, 175, 166, 174, 164,
    175, 24, 169, 96, 141, 212, 223, 8, 72, 138, 72, 162, 4, 189, 215, 223,
    149, 251, 202, 16, 248, 104, 170, 169, 4, 141, 2, 222, 169, 0, 133, 1,
    104, 40, 88, 0, 0, 0, 255, 255, 255, 255, 255, 169, 76, 141, 212, 223,
    173, 16, 223, 141, 213, 223, 173, 17, 223, 141, 214, 223, 165, 153, 208,
    57, 165, 208, 208, 53, 132, 253, 173, 20, 223, 208, 3, 160, 12, 44, 160,
    0, 185, 28, 130, 240, 8, 32, 22, 231, 230, 200, 200, 208, 243, 141, 146,
    2, 133, 211, 133, 212, 230, 208, 164, 253, 206, 20, 223, 16, 12, 173, 16,
    223, 141, 36, 3, 173, 17, 223, 141, 37, 3, 76, 184, 223, 76, 79, 65, 68,
    34, 42, 34, 44, 56, 44, 49, 0, 82, 85, 78, 0, 164, 183, 240, 66, 192, 17,
    176, 83, 136, 185, 21, 223, 201, 32, 240, 248, 200, 132, 191, 169, 74,
    133, 251, 169, 131, 133, 252, 24, 165, 251, 105, 24, 133, 251, 144, 2,
    230, 252, 160, 0, 177, 251, 240, 26, 185, 21, 223, 201, 42, 240, 17, 209,
    251, 208, 228, 200, 196, 191, 208, 240, 192, 16, 240, 4, 177, 251, 208,
    215, 24, 96, 56, 96, 24, 169, 96, 141, 212, 223, 76, 184, 223, 165, 147,
    208, 6, 165, 186, 201, 8, 240, 26, 169, 76, 141, 212, 223, 173, 18, 223,
    141, 213, 223, 173, 19, 223, 141, 214, 223, 165, 147, 166, 195, 164, 196,
    76, 184, 223, 32, 44, 130, 176, 225, 169, 175, 141, 90, 223, 169, 245,
    141, 91, 223, 32, 84, 223, 173, 20, 223, 48, 18, 162, 0, 160, 0, 161, 0,
    161, 0, 161, 0, 161, 0, 232, 208, 245, 200, 208, 242, 169, 210, 141, 90,
    223, 169, 245, 141, 91, 223, 32, 84, 223, 160, 16, 177, 251, 24, 109, 0,
    223, 133, 253, 200, 200, 177, 251, 133, 254, 200, 177, 251, 133, 255, 200,
    177, 251, 133, 174, 200, 177, 251, 133, 175, 200, 177, 251, 72, 200, 177,
    251, 133, 252, 104, 133, 251, 165, 185, 208, 8, 165, 195, 133, 174, 165,
    196, 133, 175, 24, 165, 251, 101, 254, 133, 251, 144, 2, 230, 252, 56,
    165, 174, 229, 254, 133, 174, 176, 2, 198, 175, 164, 254, 169, 0, 133,
    254, 141, 160, 223, 165, 252, 240, 3, 76, 104, 223, 140, 160, 223, 76,
    145, 223,
])  # 826 bytes — lo (lower 8KB) mode kernel API

LAUNCHER_HI = bytes([
    169, 7, 141, 2, 222, 76, 0, 160, 120, 162, 8, 189, 228, 255, 149, 1, 202,
    208, 248, 240, 8, 254, 255, 237, 255, 64, 120,
])  # 27 bytes — Ultimax bank-jump launcher

STARTUP = bytes([
    0, 0, 169, 135, 141, 2, 222, 169, 0, 162, 251, 157, 255, 215, 157, 249,
    216, 157, 243, 217, 157, 237, 218, 202, 208, 241, 162, 47, 189, 195, 4, 157,
    0, 208, 202, 16, 247, 162, 30, 160, 6, 138, 153, 248, 7, 202, 136, 16,
    248, 169, 127, 141, 0, 220, 162, 255, 142, 2, 220, 232, 142, 3, 220, 162,
    0, 32, 166, 4, 32, 166, 4, 189, 179, 4, 160, 3, 153, 39, 208, 136,
    16, 250, 189, 187, 4, 141, 43, 208, 232, 224, 8, 208, 228, 162, 100, 32,
    166, 4, 173, 1, 220, 41, 224, 201, 224, 208, 42, 202, 208, 241, 162, 7,
    32, 166, 4, 32, 166, 4, 189, 179, 4, 160, 3, 153, 39, 208, 136, 16,
    250, 189, 187, 4, 141, 43, 208, 202, 16, 230, 169, 0, 141, 0, 222, 141,
    0, 223, 169, 0, 44, 169, 4, 141, 2, 222, 169, 0, 141, 2, 220, 141,
    0, 220, 141, 21, 208, 108, 252, 255, 169, 255, 205, 18, 208, 208, 251, 205,
    18, 208, 240, 251, 96, 0, 9, 11, 4, 12, 5, 15, 1, 0, 9, 11,
    4, 12, 5, 8, 8, 0, 50, 24, 50, 48, 50, 72, 50, 36, 50, 20,
    231, 44, 231, 0, 0, 31, 155, 55, 0, 0, 127, 8, 0, 20, 15, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 12, 5, 0, 120, 162, 255, 154, 216, 169, 8, 141, 22, 208, 157, 0,
    1, 202, 208, 250, 162, 0, 189, 2, 254, 157, 0, 4, 189, 2, 255, 157,
    0, 5, 189, 0, 248, 157, 0, 6, 189, 0, 249, 157, 0, 7, 202, 208,
    229, 173, 1, 254, 141, 145, 4, 173, 0, 254, 141, 137, 4, 76, 0, 4,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 254, 255, 244, 254, 64, 255,
])  # 512 bytes — startup / boot splash screen code

SPRITES = bytes([
    0, 0, 0, 0, 0, 0, 124, 62, 31, 254, 127, 63, 198, 99, 49, 198, 99, 49,
    198, 3, 48, 198, 3, 48, 198, 3, 48, 254, 127, 63, 254, 127, 63, 192, 99,
    1, 192, 99, 1, 192, 99, 1, 198, 99, 49, 198, 99, 49, 254, 127, 63, 124,
    62, 31, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24, 192, 1, 152,
    192, 3, 152, 192, 3, 152, 192, 3, 24, 192, 3, 24, 192, 3, 24, 192, 3, 159,
    192, 3, 159, 192, 3, 128, 192, 3, 128, 192, 3, 128, 192, 3, 152, 192, 3,
    152, 192, 3, 159, 192, 3, 15, 128, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 243, 3, 225, 243, 7, 243, 3, 6, 51, 3, 6, 51, 3, 0, 51, 3, 0,
    51, 3, 0, 51, 227, 7, 243, 227, 7, 243, 3, 6, 48, 3, 6, 48, 3, 6, 48, 3,
    6, 51, 3, 6, 51, 3, 231, 243, 1, 227, 225, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 241, 140, 0, 249, 140, 0, 25, 140, 0, 25, 140, 0, 1,
    140, 0, 1, 140, 0, 1, 140, 0, 249, 252, 0, 249, 140, 0, 25, 140, 0, 25,
    140, 0, 25, 140, 0, 25, 140, 0, 25, 140, 0, 249, 140, 0, 241, 140, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 16, 0, 0, 24, 0, 0, 24, 0, 0, 28, 0,
    0, 28, 0, 0, 28, 0, 0, 14, 0, 0, 14, 0, 0, 255, 0, 0, 255, 0, 0, 112, 0,
    0, 112, 0, 0, 56, 0, 0, 56, 0, 0, 56, 0, 0, 24, 0, 0, 24, 0, 0, 8, 0, 0,
    8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 128, 1,
    0, 64, 2, 0, 32, 2, 56, 32, 2, 68, 32, 2, 71, 32, 2, 64, 32, 2, 71, 32,
    2, 68, 32, 2, 56, 32, 2, 0, 32, 1, 0, 64, 0, 255, 128, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 255, 255, 128, 128, 0, 128, 186, 174, 128, 162, 164, 128, 185, 36, 128,
    162, 164, 128, 186, 164, 128, 128, 0, 128, 255, 255, 128, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 248,
    124, 249, 252, 254, 25, 140, 198, 25, 140, 198, 25, 140, 198, 25, 140,
    198, 25, 140, 198, 249, 252, 198, 249, 252, 198, 1, 240, 198, 1, 176, 198,
    1, 184, 198, 1, 152, 198, 1, 156, 198, 1, 140, 254, 1, 140, 124, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 62, 0, 0, 127, 0, 0, 99, 0, 0, 99,
    0, 0, 96, 0, 0, 96, 0, 0, 96, 0, 0, 111, 0, 0, 111, 0, 0, 99, 0, 0, 99,
    0, 0, 99, 0, 0, 99, 0, 0, 99, 0, 0, 127, 0, 0, 62, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0,
])  # 576 bytes — EasyFlash boot splash sprites

# ===========================================================================
# CRT FORMAT CONSTANTS  (from cart.h)
# ===========================================================================

CART_SIGNATURE = b'C64 CARTRIDGE   '  # exactly 16 bytes
CHIP_SIGNATURE  = b'CHIP'             # 4 bytes
CART_TYPE_EASYFLASH       = 32
CART_TYPE_EASYFLASH_XBANK = 33
MAX_BANKS = 63  # one less than EasyFlash max — bank 0 is reserved for startup

# ===========================================================================
# DISK ENTRY  (equivalent to struct m2i in m2i.h)
# ===========================================================================

class Entry:
    """
    Represents one entry from a disk image or M2I file.
    type: '*' = disk header, 'p' = PRG, 'd' = DEL, 'q' = listing-only PRG
    """
    __slots__ = ('name', 'id', 'type', 'data', 'length')

    def __init__(self, name: str, etype: str,
                 data: bytes = b'', disk_id: str = ''):
        self.name   = name[:16]
        self.id     = disk_id[:6]
        self.type   = etype
        self.data   = data
        self.length = len(data)


# ===========================================================================
# SECTOR OFFSET HELPERS
# ===========================================================================

def get_d64_offset(track: int, sector: int) -> int:
    """1541 (D64) byte offset for a given track/sector."""
    if track <= 17:
        offset = (track - 1) * 21
    elif track <= 24:
        offset = 17 * 21 + (track - 18) * 19
    elif track <= 30:
        offset = 17 * 21 + 7 * 19 + (track - 25) * 18
    else:
        offset = 17 * 21 + 7 * 19 + 6 * 18 + (track - 31) * 17
    return (offset + sector) * 256

# Alias used internally so both names resolve correctly.
_d64_sector_offset = get_d64_offset

def get_d81_offset(track: int, sector: int) -> int:
    """1581 (D81) byte offset: 80 tracks × 40 sectors × 256 bytes."""
    return ((track - 1) * 40 + sector) * 256

# ===========================================================================
# D64 / D81 LOW-LEVEL HELPERS  (shared by parse_d64 and parse_d81)
# ===========================================================================

def _read_sector(img: bytes, track: int, sector: int,
                 offset_fn=None) -> bytes:
    """Return the raw 256-byte sector using the supplied offset function."""
    if offset_fn is None:
        offset_fn = get_d64_offset
    off = offset_fn(track, sector)
    return img[off: off + 256]


def _petscii_name(raw: bytes) -> str:
    """
    Convert a PETSCII filename to a plain Python string.
    Stops at the first 0xA0 padding byte (standard CBM padding) or 0x00
    (used by some D81 formatters instead of 0xA0).
    """
    chars = []
    for b in raw:
        if b == 0xA0 or b == 0x00:
            break
        chars.append(chr(b))
    return ''.join(chars)


def _petscii_to_screen(name: str, max_len: int = 0) -> bytes:
    """
    Convert a PETSCII disk-name string (from _petscii_name) to C64 screen
    codes.  Handles uppercase PETSCII (0x41–0x5A) AND the shifted/lowercase
    range (0x61–0x7A, 0xC1–0xDA) that some 1581 formatters write, so the
    boot banner always shows the correct disk name regardless of which tools
    created the image.

    If max_len > 0 the result is padded with spaces to exactly max_len bytes
    (used by the multi-disk menu builder).
    """
    src = name.upper()[:max_len] if max_len else name.upper()
    length = max_len if max_len else len(src)
    out = bytearray(length)
    for i, ch in enumerate(src):
        b = ord(ch)
        if 0x41 <= b <= 0x5A:         # A-Z (ASCII / upper PETSCII)
            out[i] = b - 0x40         # → screen codes 1-26
        elif 0xC1 <= b <= 0xDA:       # PETSCII shifted letters after upper()
            out[i] = b - 0xC0
        elif b == 0x20:
            out[i] = 0x20             # space
        elif 0x30 <= b <= 0x39:
            out[i] = b                # digits same in screen codes
        elif b == 0x2D:
            out[i] = 0x2D             # hyphen
        else:
            out[i] = 0x2E             # dot fallback
    return bytes(out)


def _read_file_chain(img: bytes, start_track: int, start_sector: int,
                     offset_fn=None) -> bytes:
    """Follow a CBM sector chain and return the concatenated file data.

    A visited-set guards against corrupt images with circular sector chains;
    if a cycle is detected the chain is truncated and a warning is printed.
    """
    if offset_fn is None:
        offset_fn = get_d64_offset
    data    = bytearray()
    track, sector = start_track, start_sector
    visited: set  = set()
    while track != 0:
        if (track, sector) in visited:
            print(
                f"Warning: circular sector chain at track {track} sector {sector}"
                f" -- truncating",
                file=sys.stderr,
            )
            break
        visited.add((track, sector))
        sec         = _read_sector(img, track, sector, offset_fn)
        next_track  = sec[0]
        next_sector = sec[1]
        if next_track == 0:
            data.extend(sec[2: next_sector + 1])
        else:
            data.extend(sec[2:256])
        track  = next_track
        sector = next_sector
    return bytes(data)


# ===========================================================================
# D64 PARSER  (1541, 35-track, 683 blocks)
# ===========================================================================

def parse_d64(filename: str) -> List[Entry]:
    """
    Parse a D64 disk image (MFM, 1541 format).
    Returns a list whose first element is the disk header Entry (type='*')
    followed by one Entry per directory slot.
    """
    with open(filename, 'rb') as f:
        img = f.read()

    # Validate: standard D64 = 174848 bytes; with error bytes = 175531
    if len(img) not in (174848, 175531):
        print(
            f"Warning: {filename} is {len(img)} bytes "
            f"(expected 174848 for a standard D64); continuing anyway.",
            file=sys.stderr,
        )

    entries: List[Entry] = []

    # --- Disk header: track 18, sector 0 ---
    bam = _read_sector(img, 18, 0, get_d64_offset)
    disk_name = _petscii_name(bam[0x90: 0x90 + 16])   # offset 144
    disk_id   = _petscii_name(bam[0xA2: 0xA2 + 5])    # offset 162
    entries.append(Entry(disk_name, '*', disk_id=disk_id))

    # --- Directory: starts at track 18, sector 1 ---
    dir_track, dir_sector = 18, 1
    visited_dir: set = set()
    while dir_track != 0:
        if (dir_track, dir_sector) in visited_dir:
            print(
                f"Warning: circular directory chain at track {dir_track} "
                f"sector {dir_sector} -- truncating",
                file=sys.stderr,
            )
            break
        if not (1 <= dir_track <= 35):
            print(
                f"Warning: invalid directory link to track {dir_track} "
                f"sector {dir_sector} -- stopping",
                file=sys.stderr,
            )
            break
        visited_dir.add((dir_track, dir_sector))
        sec = _read_sector(img, dir_track, dir_sector, get_d64_offset)
        dir_track  = sec[0]
        dir_sector = sec[1]

        # 8 directory entries per sector, 32 bytes each, beginning at byte 2
        for i in range(8):
            base = 2 + i * 32
            slot = sec[base: base + 32]

            file_type_raw = slot[0]
            if not (file_type_raw & 0x80):
                continue  # empty, scratched, or not properly closed

            ft_id = file_type_raw & 0x07
            if ft_id == 0:
                ft = 'd'   # DEL
            elif ft_id == 2:
                ft = 'p'   # PRG
            else:
                print(f"Warning: unsupported CBM file type {ft_id} — skipping",
                      file=sys.stderr)
                continue

            file_track  = slot[1]
            file_sector = slot[2]
            name        = _petscii_name(slot[3: 3 + 16])

            if ft == 'd':
                entries.append(Entry(name, 'd'))
            else:
                try:
                    file_data = _read_file_chain(img, file_track, file_sector,
                                                 get_d64_offset)
                    entries.append(Entry(name, 'p', data=file_data))
                except Exception as ex:
                    print(f"Warning: cannot read '{name}': {ex}", file=sys.stderr)

    return entries


# ===========================================================================
# D81 PARSER  (1581, 80-track, 3200-block MFM format)
#
# Layout differences from D64:
#   • 80 tracks × 40 sectors × 256 bytes  =  819 200 bytes
#   • BAM:  Track 40, Sector 1  (first BAM sector; sector 2 is the second half)
#           Disk name at BAM1 offset 0x04, 16 bytes
#           Disk ID   at BAM1 offset 0x16, 5 bytes  (2-char + 0xA0 + 2-char)
#   • Directory starts at Track 40, Sector 3
#   • Directory sectors: first two bytes are next-track / next-sector as usual,
#     but track 0 / sector 255 means "last sector" (all 8 entries valid up to
#     the byte count stored in sector[1] when track==0).
#     In practice the 1581 uses the same chain-termination convention as the
#     1541 (track=0, sector=last_used_byte), so the generic chain reader works.
#   • Directory entries are 32 bytes each, 8 per sector, starting at byte 0
#     (NOT byte 2 as in D64).  The first sector starts at byte 2 because bytes
#     0–1 are the forward-link; subsequent sectors also start at byte 2.
#     → We read consistently from byte 2 of every directory sector, same as D64.
#   • File type byte is at slot offset 0 (same as D64).
#   • Start track/sector at slot offsets 1 and 2 (same as D64).
#   • File name at slot offsets 3–18 (same as D64).
# ===========================================================================

# Standard D81 image size: 80 tracks × 40 sectors × 256 bytes
D81_SIZE         = 819_200
D81_BAM_TRACK    = 40
D81_BAM_SECTOR   = 1          # first BAM sector (sector 2 is second half)
D81_DIR_TRACK    = 40
D81_DIR_SECTOR   = 3

# Offsets within the first BAM sector
D81_BAM_NAME_OFF = 0x04       # disk name, 16 bytes
D81_BAM_ID_OFF   = 0x16       # disk ID,   5 bytes  (aa 0xA0 bb cc format)

def parse_d81(filename: str) -> List[Entry]:
    """
    Parse a D81 disk image (1581, 80-track, 3200-block MFM format).
    Returns a list whose first element is the disk header Entry (type='*')
    followed by one Entry per directory slot.
    """
    with open(filename, 'rb') as f:
        img = f.read()

    if len(img) != D81_SIZE:
        print(
            f"Warning: {filename} is {len(img)} bytes "
            f"(expected {D81_SIZE} for a standard D81); continuing anyway.",
            file=sys.stderr,
        )

    entries: List[Entry] = []

    # --- Disk header: BAM at Track 40, Sector 1 ---
    bam = _read_sector(img, D81_BAM_TRACK, D81_BAM_SECTOR, get_d81_offset)
    disk_name = _petscii_name(bam[D81_BAM_NAME_OFF: D81_BAM_NAME_OFF + 16])
    disk_id   = _petscii_name(bam[D81_BAM_ID_OFF:   D81_BAM_ID_OFF + 5])
    entries.append(Entry(disk_name, '*', disk_id=disk_id))

    # --- Directory: starts at Track 40, Sector 3 ---
    dir_track, dir_sector = D81_DIR_TRACK, D81_DIR_SECTOR
    visited_dir: set = set()
    while dir_track != 0:
        if (dir_track, dir_sector) in visited_dir:
            print(
                f"Warning: circular directory chain at track {dir_track} "
                f"sector {dir_sector} -- truncating",
                file=sys.stderr,
            )
            break
        if not (1 <= dir_track <= 80):
            print(
                f"Warning: invalid directory link to track {dir_track} "
                f"sector {dir_sector} -- stopping",
                file=sys.stderr,
            )
            break
        visited_dir.add((dir_track, dir_sector))
        sec = _read_sector(img, dir_track, dir_sector, get_d81_offset)
        dir_track  = sec[0]
        dir_sector = sec[1]

        # 8 directory entries per sector, 32 bytes each, beginning at byte 2
        for i in range(8):
            base = 2 + i * 32
            slot = sec[base: base + 32]

            file_type_raw = slot[0]
            if not (file_type_raw & 0x80):
                continue  # empty, scratched, or not properly closed

            ft_id = file_type_raw & 0x07
            if ft_id == 0:
                ft = 'd'   # DEL
            elif ft_id == 2:
                ft = 'p'   # PRG
            else:
                print(f"Warning: unsupported CBM file type {ft_id} — skipping",
                      file=sys.stderr)
                continue

            file_track  = slot[1]
            file_sector = slot[2]
            name        = _petscii_name(slot[3: 3 + 16])

            if ft == 'd':
                entries.append(Entry(name, 'd'))
            else:
                try:
                    file_data = _read_file_chain(img, file_track, file_sector,
                                                 get_d81_offset)
                    entries.append(Entry(name, 'p', data=file_data))
                except Exception as ex:
                    print(f"Warning: cannot read '{name}': {ex}", file=sys.stderr)

    return entries

# ===========================================================================
# UNIFIED DISK IMAGE PARSER
# ===========================================================================

def parse_disk(filename: str) -> List[Entry]:
    """
    Dispatch to the correct parser based on file extension.
    Supports .d64, .d81, and .m2i.
    """
    ext = os.path.splitext(filename)[1].lower()
    if ext == '.d64':
        return parse_d64(filename)
    elif ext == '.d81':
        return parse_d81(filename)
    elif ext == '.m2i':
        return parse_m2i(filename)
    else:
        sys.exit(f"Unsupported disk format: '{ext}'  (use .d64, .d81, or .m2i)")


# ===========================================================================
# M2I FILE PARSER  (replaces m2i.c)
# ===========================================================================

def parse_m2i(filename: str) -> List[Entry]:
    """
    Parse an M2I mapping file.
    Format per line (after the header):  TYPE:host_filename:C64 name
    Returns a list with header Entry first.
    """
    m2i_dir = os.path.dirname(os.path.abspath(filename))
    entries: List[Entry] = []

    with open(filename, 'r', errors='replace') as f:
        raw = f.read()

    # Normalise line endings
    lines = raw.replace('\r\n', '\n').replace('\r', '\n').split('\n')
    if not lines:
        sys.exit(f"Empty M2I file: {filename}")

    # First non-empty line is the disk name
    disk_name = lines[0][:16].rstrip()
    entries.append(Entry(disk_name, '*', disk_id='EF 2A'))

    for line in lines[1:]:
        line = line.rstrip('\n')
        if not line or line.startswith('#'):
            continue

        # Split on first two colons
        col1 = line.find(':')
        col2 = line.find(':', col1 + 1) if col1 >= 0 else -1
        if col1 < 0 or col2 < 0:
            sys.exit(f"M2I parse error: '{line}'")

        etype     = line[0].lower()
        host_file = line[col1 + 1: col2].rstrip()
        c64_name  = line[col2 + 1:].rstrip()[:16]

        if etype not in ('p', 'd', 'q'):
            sys.exit(f"M2I bad type in: '{line}'")

        if etype in ('p', 'q'):
            host_path = os.path.join(m2i_dir, host_file)
            try:
                with open(host_path, 'rb') as f:
                    data = f.read()
            except IOError:
                sys.exit(f"Cannot open M2I file: '{host_path}'")
            entries.append(Entry(c64_name, etype, data=data))
        else:
            entries.append(Entry(c64_name, 'd'))

    return entries


# ===========================================================================
# BASIC LISTING BUILDER  (from disk2easyflash.c)
# Builds the synthetic "$" LOAD-and-LIST directory program.
# ===========================================================================

_TXT_PRG         = b'PRG'
_TXT_DEL         = b'DEL'
_TXT_BLOCKS_FREE = b'BLOCKS FREE.'


def build_listing(entries: List[Entry], blocks_free: int = 2) -> Entry:
    """
    Build a C64 BASIC listing (the '$' directory file) and return it as
    an Entry so it can be bundled into the cartridge alongside the real files.
    """
    buf = bytearray()

    # BASIC load address ($0401)
    buf += b'\x01\x04'

    # --- Header line: 0  "DISK NAME"  ID ---
    header = entries[0]
    name_bytes = header.name.encode('latin-1', errors='replace')[:16]
    line = bytearray()
    line += b'\x01\x01'          # next-line pointer (placeholder, C64 fixes it)
    line += b'\x00\x00'          # line number 0
    line.append(0x12)             # REVERSE ON
    line.append(0x22)             # QUOTE "
    line += name_bytes
    line += b'\x20' * (16 - len(name_bytes))  # pad to 16
    line.append(0x22)             # QUOTE "
    line.append(0x20)             # SPACE
    line += header.id.encode('latin-1', errors='replace')[:5]
    line.append(0x00)             # end of line
    buf += bytes(line)

    # --- One line per file entry ---
    for entry in entries[1:]:
        if entry.type == '*':
            continue
        size  = (entry.length + 253) // 254
        ftype = _TXT_DEL if entry.type == 'd' else _TXT_PRG

        line = bytearray()
        line += b'\x01\x01'                    # next-line pointer
        line += bytes([size & 0xFF, size >> 8])  # line number = block count

        # Left-pad size number with spaces so the filename column lines up
        spaces = 3 if size < 10 else (2 if size < 100 else 1)
        line += b'\x20' * spaces

        line.append(0x22)  # "
        fname = entry.name.encode('latin-1', errors='replace')[:16]
        line += fname
        line.append(0x22)  # "
        line += b'\x20' * (17 - len(fname))  # pad so type is always at col 20
        line += ftype
        line.append(0x00)
        buf += bytes(line)

    # --- Last line: N  BLOCKS FREE. ---
    line = bytearray()
    line += b'\x01\x01'
    line += bytes([blocks_free & 0xFF, blocks_free >> 8])
    line += _TXT_BLOCKS_FREE
    line.append(0x00)
    buf += bytes(line)

    # End of BASIC program
    buf += b'\x00\x00'

    return Entry('$', 'p', data=bytes(buf))


# ===========================================================================
# CRT / XBANK BUILDER  (replaces bundle.c + disk2easyflash.c output section)
# ===========================================================================

# Each directory entry in flash: name(16) + bank(2) + offset(2) +
#                                 loadaddr(2) + size(2)  =  24 bytes
_DIR_ENTRY_SIZE = 24


def write_cart_header(out, cart_type: int, exrom: int, game: int, name: str):
    """Write the 64-byte CRT file header."""
    hdr = bytearray(64)
    hdr[0:16]  = CART_SIGNATURE
    struct.pack_into('>I', hdr, 16, 0x40)         # header length = 64
    hdr[20], hdr[21] = 0x01, 0x00                 # version 1.0
    struct.pack_into('>H', hdr, 22, cart_type)
    hdr[24] = exrom
    hdr[25] = game
    # bytes 26-31 reserved (already 0)
    name_b = name.encode('ascii', errors='replace')[:32]
    hdr[32: 32 + len(name_b)] = name_b
    out.write(bytes(hdr))


def _write_chip_header(out, bank_hi: int, bank_lo: int, load_hi: int):
    """Write a single 16-byte CHIP packet header for an 8 KB ROM page."""
    hdr = bytearray(16)
    hdr[0:4]  = CHIP_SIGNATURE
    struct.pack_into('>I', hdr, 4, 0x2010)  # total packet = 16 + 8192
    # hdr[8:10] = chip type 0 (ROM) — already zero
    hdr[10] = bank_hi
    hdr[11] = bank_lo
    hdr[12] = load_hi   # load address high byte: 0x80=$8000 or 0xA0=$A000
    # hdr[13] = 0x00
    hdr[14] = 0x20      # ROM size high byte → 0x2000 = 8 KB
    # hdr[15] = 0x00
    out.write(bytes(hdr))


def write_bank0_crt(out, mode: str):
    """
    Write the startup bank (bank 0) for CRT mode.
    Contains sprites at +$1800 and the boot-splash/startup code at +$1E00.
    Bank 0 occupies only the hi half ($A000) of EasyFlash bank 0.
    """
    buf = bytearray(b'\xff' * 0x2000)
    buf[0x1800: 0x1800 + len(SPRITES)] = SPRITES
    buf[0x1E00: 0x1E00 + len(STARTUP)] = STARTUP

    # Patch startup: bytes 0/1 hold the target bank number and EasyFlash mode
    patch = 0x2000 - len(STARTUP)   # = 0x1E00
    buf[patch + 0] = 1              # jump to bank 1 after splash
    buf[patch + 1] = {'nm': 7, 'lo': 6, 'hi': 5}[mode]

    _write_chip_header(out, bank_hi=0, bank_lo=0, load_hi=0xA0)  # bank 0, $A000
    out.write(bytes(buf))


def bundle(out, entries: List[Entry],
           bank_size: int, bank_offset: int, bank_shift: int,
           api: bytes, launcher: Optional[bytes],
           first_bank: int):
    """
    Pack all PRG files into flash memory and write CHIP packets to `out`.

    bank_size   – bytes per logical bank (0x4000 normal, 0x2000 lo/hi)
    bank_offset – base load address ($8000 or $A000)
    bank_shift  – right-shift to get bank index from byte position (14 or 13)
    api         – compiled 6502 loader (KAPI_NM / KAPI_LO / KAPI_HI)
    launcher    – compiled Ultimax bank-jump launcher, or None
    first_bank  – first CRT bank number to use (0=xbank, 1=crt)
    """
    flash = bytearray(b'\xff' * (MAX_BANKS * 0x4000))
    flash_size = len(flash)
    pos   = 0

    # 1. Write the kernel API (6502 loader code)
    flash[pos: pos + len(api)] = api
    pos += len(api)

    # 2. Write the 40-byte disk-name banner (C64 screen codes, centred)
    # Layout: [padding][****][ ][name][ ][****] -- must fit in 40 bytes.
    # Clamp name to 30 chars; guard center against going negative.
    raw_name  = entries[0].name.rstrip()[:30]
    n         = len(raw_name)
    center    = max(0, (31 - n) // 2)
    banner    = bytearray(b'\x20' * 40)
    scr_name  = _petscii_to_screen(raw_name)   # handles all PETSCII letter ranges
    for k in range(4):
        if center + k < 40:
            banner[center + k] = 0x2A
    for k, sc in enumerate(scr_name):
        idx = center + 5 + k
        if idx < 40:
            banner[idx] = sc
    for k in range(1, 5):
        idx = center + 5 + n + k
        if idx < 40:
            banner[idx] = 0x2A
    flash[pos: pos + 40] = banner
    pos += 40

    # 3. Reserve directory space (count how many PRG entries we have)
    prg_entries = [e for e in entries[1:] if e.type == 'p']
    dir_start   = pos
    pos        += len(prg_entries) * _DIR_ENTRY_SIZE

    # 4. End-of-directory marker
    flash[pos] = 0x00
    pos += 1

    if pos > flash_size:
        sys.exit(
            f"Flash overflow: API + directory headers alone exceed "
            f"{MAX_BANKS} banks ({MAX_BANKS * 0x4000 // 1024} KiB). "
            f"Too many files?"
        )

    # 5. Ultimax launcher at the very end of the first bank (hi mode only)
    if launcher is not None:
        launcher_start = bank_size - len(launcher)
        if pos > launcher_start:
            sys.exit(
                f"Flash overflow: API + directory ({pos} bytes) overlaps the "
                f"Ultimax launcher region at offset {launcher_start:#x}. "
                f"Too many files in hi mode?"
            )
        flash[launcher_start: bank_size] = launcher
        pos = bank_size

    # 6. Write file data and fill in directory entries
    dir_pos = dir_start
    for entry in prg_entries:
        bank   = pos >> bank_shift
        offset = (pos & (bank_size - 1)) + bank_offset
        # PRG files must have at least 2 bytes (load address lo + hi).
        # Guard against corrupt/truncated entries so we get a clean error
        # instead of an IndexError.
        if entry.length < 2:
            print(
                f"Warning: skipping '{entry.name}' — PRG data is only "
                f"{entry.length} byte(s) (need at least a 2-byte load address).",
                file=sys.stderr,
            )
            dir_pos += _DIR_ENTRY_SIZE
            continue
        size   = entry.length - 2   # strip the 2-byte PRG load address

        # File payload overflow check — done BEFORE writing the directory entry
        # so we never commit a partial/invalid record.
        if pos + size > flash_size:
            sys.exit(
                f'Flash overflow: file "{entry.name}" would push data past the '
                f'{MAX_BANKS}-bank limit ({MAX_BANKS * 0x4000 // 1024} KiB). '
                f'Remove some files or use fewer disk images.'
            )

        # Directory entry: name(16) + bank(2,lo/hi) + offset(2,lo/hi)
        #                + load_addr(2,lo/hi) + size(2,lo/hi)
        name_b = entry.name.encode('latin-1', errors='replace')[:16]
        name_b = name_b.ljust(16, b'\x00')
        flash[dir_pos:          dir_pos + 16] = name_b
        flash[dir_pos + 16]  = bank   & 0xFF
        flash[dir_pos + 17]  = (bank   >> 8) & 0xFF
        flash[dir_pos + 18]  = offset & 0xFF
        flash[dir_pos + 19]  = (offset >> 8) & 0xFF
        flash[dir_pos + 20]  = entry.data[0]   # load address lo
        flash[dir_pos + 21]  = entry.data[1]   # load address hi
        flash[dir_pos + 22]  = size   & 0xFF
        flash[dir_pos + 23]  = (size   >> 8) & 0xFF   # mask: size is 16-bit in flash dir
        dir_pos += _DIR_ENTRY_SIZE

        # File payload (skip the 2-byte load address prefix)
        flash[pos: pos + size] = entry.data[2: 2 + size]
        pos += size

    # 7. Write CHIP packets — one per 8 KB page
    num_pages = (pos + 0x1FFF) >> 13  # round up to 8 KB pages
    max_pages = (flash_size) >> 13    # hard ceiling from flash buffer
    if num_pages > max_pages:
        sys.exit(
            f"Flash overflow: {num_pages} 8 KiB pages needed but EasyFlash "
            f"supports at most {max_pages} ({MAX_BANKS} banks)."
        )

    for page in range(num_pages):
        if bank_size == 0x4000:
            # 16 KB banks: pairs of 8 KB pages share a bank number
            doubled = (first_bank << 1) + page
            bank_hi  = (doubled >> 1) >> 8       # high byte of bank number
            bank_lo  = (doubled >> 1) & 0xFF     # low byte of bank number
            load_hi  = 0x80 + (0x20 if page & 1 else 0x00)  # $8000 or $A000
        else:
            # 8 KB banks
            bn       = first_bank + page
            bank_hi  = bn >> 8
            bank_lo  = bn & 0xFF
            load_hi  = (0x8000 | (bank_offset & 0x2000)) >> 8

        _write_chip_header(out, bank_hi, bank_lo, load_hi)
        out.write(bytes(flash[page << 13: (page << 13) + 0x2000]))

    # 8. Summary
    last_bytes = pos - ((num_pages - 1) << 13) if num_pages else 0
    if bank_size == 0x4000:
        half = '.5' if num_pages & 1 else ''
        print(
            f"disk2easyflash: {num_pages >> 1}{half} banks "
            f"({num_pages * 8} KiB) used   "
            f"({last_bytes} bytes in last 8 KiB page)",
            file=sys.stderr,
        )
    else:
        print(
            f"disk2easyflash: {num_pages} banks "
            f"({num_pages * 8} KiB) used   "
            f"({last_bytes} bytes in last 8 KiB page)",
            file=sys.stderr,
        )


# ===========================================================================
# MULTI-DISK MENU  -- boot menu for multiple disk images
# ===========================================================================

def _disk_key(i: int) -> str:
    """Return the keyboard shortcut for disk slot i (0-based): '1'-'9' then 'A'-'Z'."""
    return str(i + 1) if i < 9 else chr(ord('A') + i - 9)


def _build_menu_prg(disk_names: list, bank_numbers: list) -> bytes:
    """
    Build a C64 PRG (load address $080D) containing a boot menu.
    Accepts keys 1-9 for the first nine disks, then A-Z for disks 10-35.
    Cleanly hand-assembled 6502 with a two-pass label system.
    """
    n = len(disk_names)
    if not (1 <= n <= 35):
        raise ValueError(f"menu supports 1–35 disks, got {n}")

    LOAD   = 0x080D
    CHROUT = 0xFFD2
    GETIN  = 0xFFE4
    SCNCLR = 0xE544

    code   = bytearray()
    labels = {}
    fixups = []

    def here():
        return LOAD + len(code)

    def emit(*bs):
        code.extend(bs)

    def label(name):
        labels[name] = here()

    def ref_abs(name):
        fixups.append((len(code), name, 'abs16'))
        emit(0x00, 0x00)

    def ref_lo(name):
        fixups.append((len(code), name, 'lo'))
        emit(0x00)

    def ref_hi(name):
        fixups.append((len(code), name, 'hi'))
        emit(0x00)

    def ref_rel(name):
        fixups.append((len(code), name, 'rel8'))
        emit(0x00)

    def patch():
        for off, name, kind in fixups:
            addr = labels[name]
            if kind == 'abs16':
                code[off]   = addr & 0xFF
                code[off+1] = (addr >> 8) & 0xFF
            elif kind == 'lo':
                code[off] = addr & 0xFF
            elif kind == 'hi':
                code[off] = (addr >> 8) & 0xFF
            elif kind == 'rel8':
                delta = addr - (LOAD + off + 1)
                if not (-128 <= delta <= 127):
                    raise AssertionError(
                        f"Branch to '{name}' out of rel8 range ({delta}); "
                        "too many disk entries?"
                    )
                code[off] = delta & 0xFF

    strings     = bytearray()
    string_lbls = {}

    def defstr(name, data: bytes):
        string_lbls[name] = len(strings)
        strings.extend(data)
        strings.append(0x00)

    def jsr_print(str_label):
        emit(0xA9); ref_lo(str_label)
        emit(0x85, 0xFB)
        emit(0xA9); ref_hi(str_label)
        emit(0x85, 0xFC)
        emit(0x20); ref_abs('print_str')

    defstr('s_header', bytes([0x0D, 0x12]) + b'  *** DISK2EASYFLASH V1.1 ***  ' + bytes([0x92, 0x0D]))
    defstr('s_crd', bytes([0x20, 0x20, 0x20, 0x4D, 0x49, 0x4C, 0x41, 0x53, 0x4F, 0x46, 0x54, 0x36, 0x34, 0x2E, 0x49, 0x54, 0x43, 0x48, 0x2E, 0x49, 0x4F, 0x0D, 0x0D]))
    defstr('s_select', b'  SELECT A DISK:\r\r')
    for i, name in enumerate(disk_names):
        trunc = name.upper()[:16]
        key   = _disk_key(i)          # '1'-'9' then 'A'-'Z'
        line  = ('  ' + key + '. ' + trunc + '\r').encode('latin-1', errors='replace')
        defstr('s_disk' + str(i), line)

    # ── Preamble ─────────────────────────────────────────────────────────────
    emit(0x78)                         # SEI
    emit(0x20, SCNCLR&0xFF, SCNCLR>>8) # JSR SCNCLR
    emit(0x58)                         # CLI
    emit(0xA9, 0x00)
    emit(0x8D, 0x20, 0xD0)             # STA $D020 (border colour = black)
    emit(0x8D, 0x21, 0xD0)             # STA $D021 (bg colour = black)
    emit(0x85, 0xC6)                   # STA $C6   (198) clear keyboard buffer
    emit(0xA9, 0x01)
    emit(0x8D, 0x86, 0x02)             # STA $0286 (KERNAL char colour = white)

    emit(0x4C); ref_abs('main')        # JMP main

    # ── print_str: print NUL-terminated string pointed to by $FB/$FC ─────────
    label('print_str')
    emit(0xA0, 0x00)                   # LDY #0
    label('ps_loop')
    emit(0xB1, 0xFB)                   # LDA ($FB),Y
    emit(0xF0); ref_rel('ps_done')     # BEQ ps_done
    emit(0x20, CHROUT&0xFF, CHROUT>>8) # JSR CHROUT
    emit(0xC8)                         # INY
    emit(0xD0); ref_rel('ps_loop')     # BNE ps_loop
    emit(0xE6, 0xFC)                   # INC $FC  (high byte of pointer)
    emit(0xD0); ref_rel('ps_loop')     # BNE ps_loop
    label('ps_done')
    emit(0x60)                         # RTS

    # ── main: disk list ────────────────────────
    label('main')
    jsr_print('s_header')
    jsr_print('s_crd')
    jsr_print('s_select')
    for i in range(n):
        jsr_print(f's_disk{i}')

    # ── wait_key: accept '1'-'9' (disks 1-9) and 'A'-'Z'/'a'-'z' (10-35) ───
    #
    # Key → 0-based index mapping:
    #   '1'..'9'  (0x31..0x39)  →  index 0..8
    #   'A'..'Z'  (0x41..0x5A)  →  index 9..34
    #   'a'..'z'  (0x61..0x7A)  →  index 9..34  (same as uppercase)
    #
    label('wait_key')
    emit(0x20, GETIN&0xFF, GETIN>>8)  # JSR GETIN  → key in A

    # --- digits '1'-'9' ---
    emit(0xC9, 0x31)                   # CMP #'1'
    emit(0x90); ref_rel('wait_key')    # BCC wait_key  (< '1')
    emit(0xC9, 0x3A)                   # CMP #'9'+1
    emit(0xB0); ref_rel('try_upper')   # BCS try_upper (> '9')
    emit(0x38)                         # SEC
    emit(0xE9, 0x31)                   # SBC #'1'   →  A = 0..8
    emit(0x4C); ref_abs('got_index')   # JMP got_index

    # --- uppercase A-Z ---
    label('try_upper')
    emit(0xC9, 0x41)                   # CMP #'A'
    emit(0x90); ref_rel('wait_key')    # BCC wait_key  (gap between ':' and 'A')
    emit(0xC9, 0x5B)                   # CMP #'Z'+1
    emit(0xB0); ref_rel('try_lower')   # BCS try_lower (> 'Z')
    emit(0x38)                         # SEC
    emit(0xE9, 0x41 - 9)               # SBC #0x38   →  A = 9..34  ('A'=9)
    emit(0x4C); ref_abs('got_index')   # JMP got_index

    # --- lowercase a-z ---
    label('try_lower')
    emit(0xC9, 0x61)                   # CMP #'a'
    emit(0x90); ref_rel('wait_key')    # BCC wait_key
    emit(0xC9, 0x7B)                   # CMP #'z'+1
    emit(0xB0); ref_rel('wait_key')    # BCS wait_key
    emit(0x38)                         # SEC
    emit(0xE9, 0x61 - 9)               # SBC #0x58   →  A = 9..34  ('a'=9)
    # fall through to got_index

    # --- got_index: A = 0-based index; validate, then jump to chosen disk ----
    label('got_index')
    emit(0xC9, n)                      # CMP #n
    emit(0xB0); ref_rel('wait_key')    # BCS wait_key  (index >= n → invalid key)
    emit(0xAA)                         # TAX
    emit(0xBD); ref_abs('bank_tbl')    # LDA bank_tbl,X
    emit(0x8D, 0x00, 0xDE)             # STA $DE00  (EasyFlash bank select)
    emit(0x8D, 0x00, 0xDF)             # STA $DF00
    emit(0xA9, 0x07)                   # LDA #$07   (EasyFlash NM mode)
    emit(0x8D, 0x02, 0xDE)             # STA $DE02
    emit(0x4C, 0x00, 0x80)             # JMP $8000  (start chosen disk's KAPI)

    # ── Append string pool and bank table, resolve all fixups ─────────────────
    strings_base = here()
    for sname, soff in string_lbls.items():
        labels[sname] = strings_base + soff

    bank_tbl_base = strings_base + len(strings)
    labels['bank_tbl'] = bank_tbl_base

    patch()

    code.extend(strings)
    for bn in bank_numbers:
        code.append(bn & 0xFF)

    basic_stub = bytes([
        0x0B, 0x08,
        0x0A, 0x00,
        0x9E,
        0x32, 0x30, 0x36, 0x31,
        0x00,
        0x00, 0x00,
    ])

    prg = bytes([0x01, 0x08]) + basic_stub + bytes(code)
    return prg


def _count_chips(data: bytes) -> int:
    """
    Count CHIP packets in raw CRT chip-section bytes by following the
    packet-length field in each header.  Much more reliable than searching
    for the literal bytes b'CHIP' which can appear inside file data.
    """
    count = 0
    pos   = 0
    while pos + 16 <= len(data):
        if data[pos:pos + 4] != b'CHIP':
            break
        pkt_len = struct.unpack_from('>I', data, pos + 4)[0]
        if pkt_len < 16:
            break          # malformed — stop
        count += 1
        pos   += pkt_len
    return count


def build_multi_crt(disk_paths: list, output_path: str, mode: str = 'nm'):
    """
    Build a multi-disk EasyFlash CRT.

    Layout:
      Bank 0  : EasyFlash startup splash (unchanged, jumps to bank 1)
      Bank 1  : Boot menu PRG packed via bundle()
      Banks 2+: One disk image each, packed via bundle()
    """
    if len(disk_paths) > 35:
        sys.exit("multi mode supports at most 35 disk images (keys 1-9, A-Z)")
    if len(disk_paths) < 2:
        sys.exit("multi mode needs at least 2 disk images")

    # Pick bundle parameters for the chosen mode.
    if mode == 'nm':
        _bsize, _boff, _bshift, _api, _launcher = 0x4000, 0x8000, 14, KAPI_NM, None
    elif mode == 'lo':
        _bsize, _boff, _bshift, _api, _launcher = 0x2000, 0x8000, 13, KAPI_LO, None
    else:  # hi
        _bsize, _boff, _bshift, _api, _launcher = 0x2000, 0xA000, 13, KAPI_HI, LAUNCHER_HI

    all_entries = []
    disk_names  = []
    for path in disk_paths:
        entries = parse_m2i(path) if path.lower().endswith('.m2i') else parse_disk(path)
        if not entries[0].name.strip():
            entries[0] = Entry(
                os.path.splitext(os.path.basename(path))[0].upper(),
                entries[0].type, disk_id=entries[0].id)
        all_entries.append(entries)
        disk_names.append(entries[0].name.strip() or os.path.splitext(os.path.basename(path))[0])
        print(f"  Loaded: {path}  ({disk_names[-1]})", file=sys.stderr)

    def dry_run_bundle(entries, first_bank):
        buf = io.BytesIO()
        bundle(buf, entries, _bsize, _boff, _bshift, _api, _launcher, first_bank)
        buf.seek(0)
        data  = buf.read()
        chips = _count_chips(data)
        return data, chips

    disk_start_banks = []
    current_bank = 2
    disk_chip_data = []
    for i, entries in enumerate(all_entries):
        disk_start_banks.append(current_bank)
        chip_data, num_chips = dry_run_bundle(entries, current_bank)
        disk_chip_data.append(chip_data)
        # nm: 2 chips per 16 KB bank; lo/hi: 1 chip per 8 KB bank
        if mode == 'nm':
            banks_used = (num_chips + 1) // 2
        else:
            banks_used = num_chips
        print(f"  Disk {i+1} ({disk_names[i]}): start bank {current_bank}, {banks_used} bank(s)", file=sys.stderr)
        current_bank += banks_used

    if current_bank > MAX_BANKS:
        sys.exit(f"Too many banks needed ({current_bank}); EasyFlash max is {MAX_BANKS}")

    menu_prg = _build_menu_prg(disk_names, disk_start_banks)
    menu_entry = Entry('MENU', 'p', data=menu_prg)
    menu_entries = [Entry('DISK2EASYFLASH', '*', disk_id='EF 2A'), menu_entry]

    with open(output_path, 'wb') as out:
        write_cart_header(out, CART_TYPE_EASYFLASH, 1, 0, 'MULTIDISK')
        write_bank0_crt(out, mode)
        bundle(out, menu_entries, _bsize, _boff, _bshift, _api, _launcher, 1)
        for chip_data in disk_chip_data:
            out.write(chip_data)

    print(f"Written: {output_path}  ({current_bank} banks used)", file=sys.stderr)




# ===========================================================================
# INTERACTIVE MENU  (run when no CLI arguments are supplied)
# ===========================================================================

_DISK_EXTS = ('.d64', '.d81', '.m2i')


def _load_disk(path: str):
    """
    Parse a disk image and ensure entries[0].name is never blank.
    If the BAM disk name is empty (some D81 images leave it blank),
    fall back to the filename stem so the boot banner always shows something.
    """
    entries = parse_m2i(path) if path.lower().endswith('.m2i') else parse_disk(path)
    if not entries[0].name.strip():
        entries[0] = Entry(
            os.path.splitext(os.path.basename(path))[0].upper(),
            entries[0].type,
            disk_id=entries[0].id,
        )
    return entries

# ---------------------------------------------------------------------------
# Terminal colour helpers  (no external deps — pure ANSI / Windows ctypes)
# ---------------------------------------------------------------------------

def _enable_ansi():
    """Enable ANSI escape codes on Windows 10+; no-op on Linux/macOS."""
    if sys.platform == 'win32':
        try:
            import ctypes
            kernel32 = ctypes.windll.kernel32          # type: ignore[attr-defined]
            # Enable ENABLE_VIRTUAL_TERMINAL_PROCESSING (0x0004) on stdout
            handle = kernel32.GetStdHandle(-11)        # STD_OUTPUT_HANDLE
            mode   = ctypes.c_ulong(0)
            if kernel32.GetConsoleMode(handle, ctypes.byref(mode)):
                kernel32.SetConsoleMode(handle, mode.value | 0x0004)
        except Exception:
            pass  # graceful fallback — text just won't be coloured

_COL_WHITE = '\033[97m'   # bright white
_COL_RESET = '\033[0m'

def _w(text: str) -> str:
    """Wrap text in bright-white ANSI colour."""
    return f'{_COL_WHITE}{text}{_COL_RESET}'

# ---------------------------------------------------------------------------
# Disk-key helpers  (1-9 for slots 1-9, A-Z for slots 10-35)
# ---------------------------------------------------------------------------

def _slot_key(n: int) -> str:
    """Python-UI display key for slot *n* (1-based): '1'-'9' then 'A'-'Z'."""
    if n <= 9:
        return str(n)
    return chr(ord('A') + n - 10)   # 10→A, 11→B, …, 35→Z


def _parse_disk_keys(raw: str, total: int) -> List[int]:
    """
    Parse a string of disk keys — tolerates any mix of whitespace, commas,
    semicolons or other punctuation as separators (e.g. '1 3', '1,2,3', '1, 2, A').
    Returns a deduplicated list of 1-based indices in the order entered.
    Accepts digits 1-9 and letters A-Z (case-insensitive).
    """
    result = []
    seen   = set()
    for tok in re.split(r'[\s,;]+', raw.upper().strip()):
        if not tok:
            continue
        if tok.isdigit():
            n = int(tok)
            if 1 <= n <= min(9, total) and n not in seen:
                result.append(n)
                seen.add(n)
        elif len(tok) == 1 and 'A' <= tok <= 'Z':
            n = ord(tok) - ord('A') + 10
            if 1 <= n <= total and n not in seen:
                result.append(n)
                seen.add(n)
    return result


_BANNER = """
  ╔══════════════════════════════════════════════════════════════╗
  ║        Disk2Easyflash by Alex Kazik. Updated by Milasoft     ║
  ║        v1.1 — Convert C64 disk images to EasyFlash carts     ║
  ╚══════════════════════════════════════════════════════════════╝
"""

_HELP_CRT_FORMAT = """
  ┌─ CRT Format Help ────────────────────────────────────────────┐
  │  EasyFlash CRT  – Standard cartridge format. Use this unless │
  │                   you have a specific reason not to.         │
  │  XBANK CRT      – Extended bank format. Only use if your     │
  │                   flash tool explicitly requires XBANK.      │
  └──────────────────────────────────────────────────────────────┘"""

_HELP_BANK_MODE = """
  ┌─ Bank Mode Help ─────────────────────────────────────────────┐
  │  Normal (16 KiB) – Uses both ROM areas ($8000 + $A000).      │
  │                    Best capacity. Recommended for beginners. │
  │  Low    ( 8 KiB) – Uses only the low ROM area ($8000).       │
  │                    Needed for games that occupy $A000.       │
  │  High   ( 8 KiB) – Uses only the high ROM area ($A000).      │
  │                    Ultimax mode; rarely needed.              │
  └──────────────────────────────────────────────────────────────┘"""


def _find_disk_images(root: str = '.') -> list:
    """
    Recursively scan *root* for disk image files (.d64 / .d81 / .m2i).
    Returns a sorted list of absolute paths.
    """
    found = []
    for dirpath, _dirs, files in os.walk(root):
        for fname in sorted(files):
            if any(fname.lower().endswith(ext) for ext in _DISK_EXTS):
                found.append(os.path.abspath(os.path.join(dirpath, fname)))
    return sorted(found)


def _short(path: str) -> str:
    """Return just the filename for display; keep full path internally."""
    return os.path.basename(path)


def _prompt(msg: str, default: str = '') -> str:
    """Show a prompt, return stripped input (or default on empty)."""
    suffix = f' [{default}]' if default else ''
    val = input(f'{_COL_WHITE}  {msg}{suffix}: {_COL_RESET}').strip()
    return val if val else default


def _choose(msg: str, options: list, default: int = 1) -> int:
    """Show numbered options; return 1-based index of chosen item."""
    print()
    for i, opt in enumerate(options, 1):
        marker = '>' if i == default else ' '
        print(_w(f'  {marker} {i}. {opt}'))
    print()
    while True:
        raw = _prompt(msg, str(default))
        try:
            n = int(raw)
            if 1 <= n <= len(options):
                return n
        except ValueError:
            pass
        print(_w(f'  Please enter a number between 1 and {len(options)}.'))


def _yn(msg: str, default: bool = True) -> bool:
    """Ask a yes/no question.  BUG-FIX: actually retries on invalid input."""
    hint = 'Y/n' if default else 'y/N'
    while True:
        raw = _prompt(f'{msg} ({hint})').lower()
        if raw == '':
            return default
        if raw in ('y', 'yes'):
            return True
        if raw in ('n', 'no'):
            return False
        print(_w("  Please answer 'y' or 'n'."))


def _pause():
    """Wait for the user to press Enter — useful at the end when run as an EXE."""
    input('\n  Press Enter to exit...')


def run_menu():
    """Interactive guided menu — launched when the script is run with no arguments."""
    _enable_ansi()
    print(_w(_BANNER))

    # ── 1. Auto-scan for disk images (sorted alphabetically) ─────────────────
    print(_w('  Scanning current folder for disk images (.d64 / .d81 / .m2i)...'))
    images = sorted(_find_disk_images('.'), key=lambda p: os.path.basename(p).lower())

    # ── 2. Show found list + integrated "add more" prompt ────────────────────
    #
    # The add-path option is shown ALONGSIDE the list so users immediately see
    # they can supplement the auto-scan.  After each addition the list refreshes.
    #
    while True:
        if images:
            print(_w(f'\n  Found {len(images)} disk image(s):\n'))
            for i, img in enumerate(images, 1):
                key = _slot_key(i)
                folder = os.path.dirname(img)
                print(_w(f'    {key:>2}.  {_short(img):<40}  ({folder})'))
        else:
            print(_w('  No disk images found in the current folder or sub-folders.'))

        print()
        extra = _prompt(
            'Drag-and-drop or type a path to add an image, or press Enter to continue'
        ).strip()
        if not extra:
            break
        extra = extra.strip('"').strip("'")
        if not os.path.isfile(extra):
            print(_w(f'  File not found: {extra}'))
            continue
        full = os.path.abspath(extra)
        if full in images:
            print(_w(f'  Already in list: {_short(full)}'))
        else:
            images.append(full)
            images.sort(key=lambda p: os.path.basename(p).lower())
            print(_w(f'  Added: {_short(full)}'))

    if not images:
        print(_w('  No disk images selected.  Exiting.'))
        _pause()
        return

    # ── 3. Single vs multi ───────────────────────────────────────────────────
    if len(images) == 1:
        cart_kind = 'single'
        print(_w(f'\n  One image found  →  building a single-disk cartridge.'))
    else:
        ck = _choose(
            'Cartridge type',
            ['Single-disk CRT  – one game / disk, most compatible',
             'Multi-disk CRT   – up to 35 disks in one cartridge with boot menu'],
        )
        cart_kind = 'single' if ck == 1 else 'multi'

    # ── 4. Select disk(s) ────────────────────────────────────────────────────
    if cart_kind == 'single':
        if len(images) == 1:
            selected = [images[0]]
        else:
            labels = [_short(p) for p in images]
            idx = _choose('Which disk image to convert?', labels)
            selected = [images[idx - 1]]
    else:
        print()
        print(_w('  Enter the keys of the disks to include (e.g.  1 3 A C),'))
        print(_w('  or press Enter to include ALL of them in the order shown.'))
        raw = input(_w('  Selection: ')).strip()
        if raw:
            idxs = _parse_disk_keys(raw, len(images))
            if idxs:
                selected = [images[i - 1] for i in idxs]
            else:
                print(_w('  Could not parse selection — using all images.'))
                selected = images
        else:
            selected = images
        if len(selected) < 2:
            print(_w('  Multi-disk mode needs at least 2 images. Exiting.'))
            _pause()
            return
        if len(selected) > 35:
            print(_w('  Multi-disk mode supports at most 35 images (keys 1-9, A-Z). Trimming to 35.'))
            selected = selected[:35]
        print()
        print(_w('  Selected disks (in order):'))
        for i, s in enumerate(selected, 1):
            print(_w(f'    {_slot_key(i):>2}.  {_short(s)}'))

    # ── 5. CRT format ────────────────────────────────────────────────────────
    print()
    if cart_kind == 'multi':
        crt_type = 'crt'
        print(_w('  Multi-disk always uses EasyFlash CRT format — no choice needed.'))
    else:
        print(_w(_HELP_CRT_FORMAT))
        ct = _choose(
            'CRT format',
            ['EasyFlash CRT   (standard — choose this if unsure)',
             'EasyFlash XBANK CRT  (only if your flash tool requires it)'],
        )
        crt_type = 'crt' if ct == 1 else 'xbank'

    # ── 6. Bank mode ─────────────────────────────────────────────────────────
    print(_w(_HELP_BANK_MODE))
    bm = _choose(
        'Bank mode',
        ['Normal 16 KiB  – best capacity, recommended for beginners',
         'Low     8 KiB  – use if the game occupies memory at $A000',
         'High    8 KiB  – Ultimax mode, rarely needed'],
    )
    mode = {1: 'nm', 2: 'lo', 3: 'hi'}[bm]

    # ── 7. Output filename ───────────────────────────────────────────────────
    print()
    first_dir = os.path.dirname(selected[0])
    if cart_kind == 'single':
        default_out = os.path.join(
            first_dir, os.path.splitext(os.path.basename(selected[0]))[0] + '.crt')
    else:
        default_out = os.path.join(first_dir, 'multidisk.crt')

    print(_w('  Where should the output .crt file be saved?'))
    print(_w(f'  (Default saves it next to your disk image)\n'))
    output_path = _prompt('Output .crt filename', default_out)
    if not output_path.lower().endswith('.crt'):
        output_path += '.crt'
    out_dir = os.path.dirname(output_path)
    if out_dir and not os.path.isdir(out_dir):
        try:
            os.makedirs(out_dir, exist_ok=True)
        except OSError as e:
            print(_w(f'  Warning: could not create output directory: {e}'))

    # ── 8. Extra single-disk options ─────────────────────────────────────────
    nolisting   = False
    blocks_free = 2
    removes     = []
    ignores     = []

    if cart_kind == 'single':
        print()
        print(_w('  ── Optional tweaks ────────────────────────────────────────────'))
        print(_w('  A LOAD "$" listing lets you see the disk directory on the C64.'))
        nolisting = not _yn('Include LOAD "$" directory listing in cartridge?', True)
        if not nolisting:
            raw_bf = _prompt('Blocks-free value shown in listing (leave at 2 if unsure)', '2')
            try:
                blocks_free = int(raw_bf)
            except ValueError:
                blocks_free = 2

        print()
        print(_w('  Previewing the file list lets you remove unwanted files from'))
        print(_w('  the cartridge before building (e.g. cracktros, save slots).'))
        show_list = _yn('Preview file list now?', True)
        if show_list:
            try:
                is_m2i_prev = selected[0].lower().endswith('.m2i')
                entries_prev = parse_m2i(selected[0]) if is_m2i_prev else parse_disk(selected[0])
                print()
                print(_w(f'  ┌─ Disk: "{entries_prev[0].name}"  {entries_prev[0].id}'))
                print(_w(f'  │  {"#":>3}  {"Blocks":>6}  {"Filename":<20}  Type'))
                print(_w(f'  ├{"─"*50}'))
                num = 0
                for e in entries_prev[1:]:
                    if e.type in ('p', 'q', 'd'):
                        num += 1
                        tag  = '  ← listing only' if e.type == 'q' else ''
                        size = (e.length + 253) // 254
                        ftype = 'DEL' if e.type == 'd' else 'PRG'
                        print(_w(f'  │  {num:>3}.  {size:>6}  "{e.name:<18}"  {ftype}{tag}'))
                print(_w(f'  └{"─"*50}'))
                print()
                print(_w('  To REMOVE a file: enter its number — it will be excluded from the'))
                print(_w('  cartridge entirely. To IGNORE: file stays in the directory listing'))
                print(_w('  but its data is not written to flash (useful for save-game slots).'))
                print()
                raw_rm = _prompt('Remove entries by number (space-separated, blank=none)').strip()
                if raw_rm:
                    removes = [int(x) for x in raw_rm.split() if x.isdigit()]
                raw_ig = _prompt('Ignore entries (blank=none)').strip()
                if raw_ig:
                    ignores = [int(x) for x in raw_ig.split() if x.isdigit()]
            except Exception as ex:
                print(_w(f'  Could not preview disk: {ex}'))

    # ── 9. Confirm and build ─────────────────────────────────────────────────
    mode_labels = {'nm': 'Normal 16 KiB', 'lo': 'Low 8 KiB', 'hi': 'High 8 KiB'}
    print()
    print(_w('  ╔══ Build Summary ═══════════════════════════════════════════╗'))
    if cart_kind == 'multi':
        print(_w(f'  ║  Type     : Multi-disk EasyFlash CRT'))
        print(_w(f'  ║  Bank mode: {mode_labels[mode]}'))
        for i, s in enumerate(selected, 1):
            label = f'Disk {_slot_key(i):>2}'
            print(_w(f'  ║  {label}   : {_short(s)}'))
    else:
        print(_w(f'  ║  Disk     : {_short(selected[0])}'))
        print(_w(f'  ║  Format   : {crt_type.upper()},  bank mode: {mode_labels[mode]}'))
        print(_w(f'  ║  Listing  : {"no" if nolisting else "yes"}'))
        if removes:
            print(_w(f'  ║  Remove   : entries {removes}'))
        if ignores:
            print(_w(f'  ║  Ignore   : entries {ignores}'))
    print(_w(f'  ║  Output   : {output_path}'))
    print(_w('  ╚════════════════════════════════════════════════════════════╝'))
    print()

    if not _yn('Build cartridge now?', True):
        print(_w('  Cancelled.  Nothing was written.'))
        _pause()
        return

    # ── 10. Execute ──────────────────────────────────────────────────────────
    try:
        if cart_kind == 'multi':
            print()
            build_multi_crt(selected, output_path, mode=mode)
        else:
            entries = _load_disk(selected[0])

            for rid in removes:
                num, done = 0, False
                for e in entries[1:]:
                    if e.type != '*':
                        num += 1
                        if num == rid:
                            e.type = '*'
                            done = True
                            break
                if not done:
                    print(_w(f'  Warning: cannot remove entry {rid}: no such entry'))

            for iid in ignores:
                num, done = 0, False
                for e in entries[1:]:
                    if e.type == 'p':
                        num += 1
                        if num == iid:
                            e.type = 'q'
                            done = True
                            break
                if not done:
                    print(_w(f'  Warning: cannot ignore entry {iid}: no such entry'))

            if not nolisting:
                listing = build_listing(entries, blocks_free)
                entries.append(listing)

            basename = os.path.basename(selected[0])
            with open(output_path, 'wb') as out:
                if crt_type == 'crt':
                    write_cart_header(out, CART_TYPE_EASYFLASH, 1, 0, basename)
                    write_bank0_crt(out, mode)
                    if mode == 'nm':
                        bundle(out, entries, 0x4000, 0x8000, 14, KAPI_NM, None, 1)
                    elif mode == 'lo':
                        bundle(out, entries, 0x2000, 0x8000, 13, KAPI_LO, None, 1)
                    else:
                        bundle(out, entries, 0x2000, 0xA000, 13, KAPI_HI, LAUNCHER_HI, 1)
                else:  # xbank
                    if mode == 'hi':
                        exrom, game = 1, 0
                    elif mode == 'lo':
                        exrom, game = 0, 1
                    else:
                        exrom, game = 0, 0
                    write_cart_header(out, CART_TYPE_EASYFLASH_XBANK, exrom, game, basename)
                    if mode == 'nm':
                        bundle(out, entries, 0x4000, 0x8000, 14, KAPI_NM, None, 0)
                    elif mode == 'lo':
                        bundle(out, entries, 0x2000, 0x8000, 13, KAPI_LO, None, 0)
                    else:
                        bundle(out, entries, 0x2000, 0xA000, 13, KAPI_HI, LAUNCHER_HI, 0)

        print()
        print(_w(f'  ✓  Done!  Cartridge written to:'))
        print(_w(f'     {output_path}'))
        print()
    except Exception as ex:
        print(_w(f'\n  ERROR: {ex}'))

    _pause()



# ===========================================================================
# CLI  (replaces main() in disk2easyflash.c)
# ===========================================================================

def _safe_excepthook(exc_type, exc_val, exc_tb):
    """
    Replace the default traceback dump so internal file paths and line numbers
    are never shown to end users.  KeyboardInterrupt prints a clean message;
    all other exceptions print only their human-readable text.
    Set DISK2EF_DEBUG=1 in your environment to restore full tracebacks.
    """
    if exc_type is KeyboardInterrupt:
        print('\n\n  Cancelled.')
    else:
        print(f'\n  Error: {exc_val}', file=sys.stderr)
        print('  (Run with DISK2EF_DEBUG=1 for full traceback)', file=sys.stderr)


def main():
    # Install safe excepthook so no internal paths/line numbers leak to users.
    # Bypass with:  set DISK2EF_DEBUG=1   (Windows)
    #               export DISK2EF_DEBUG=1  (Linux/macOS)
    if not os.environ.get('DISK2EF_DEBUG'):
        sys.excepthook = _safe_excepthook

    args_raw = sys.argv[1:]

    # ── Interactive menu when no arguments are given ─────────────────────────
    if not args_raw:
        try:
            run_menu()
        except KeyboardInterrupt:
            print('\n\n  Cancelled.')
            try:
                _pause()
            except KeyboardInterrupt:
                pass
        return

    # ── CLI mode — guard against Ctrl+C and unexpected crashes ───────────────
    try:
        _cli(args_raw)
    except KeyboardInterrupt:
        print('\n\n  Cancelled.', file=sys.stderr)
        sys.exit(1)
    except Exception as ex:
        print(f'\n  Error: {ex}', file=sys.stderr)
        if os.environ.get('DISK2EF_DEBUG'):
            raise
        sys.exit(1)


def _cli(args_raw):
    """All CLI logic, separated so main() can wrap it cleanly."""

    if '--multi' in args_raw:
        rest = [a for a in args_raw if a != '--multi']
        if len(rest) < 2:
            sys.exit('Usage: disk2easyflash --multi <disk1.d64> [disk2.d64 ...] <output.crt>')
        output_crt = rest[-1]   # output is always last
        disk_files  = rest[:-1]
        for df in disk_files:
            if not os.path.isfile(df):
                sys.exit(f'File not found: {df}')
        if len(disk_files) < 2:
            sys.exit('--multi needs at least 2 disk images')
        print(f"disk2easyflash: multi-disk mode, {len(disk_files)} images -> {output_crt}", file=sys.stderr)
        build_multi_crt(disk_files, output_crt)
        return

    non_flag  = [a for a in args_raw if not a.startswith('-')]
    disk_args = [a for a in non_flag if any(a.lower().endswith(e) for e in _DISK_EXTS)]
    crt_args  = [a for a in non_flag if a.lower().endswith('.crt')]
    if len(disk_args) >= 2 and len(crt_args) == 1:
        output_crt = crt_args[0]
        disk_files  = disk_args
        for df in disk_files:
            if not os.path.isfile(df):
                sys.exit(f'File not found: {df}')
        print(f"disk2easyflash: multi-disk mode, {len(disk_files)} images -> {output_crt}", file=sys.stderr)
        build_multi_crt(disk_files, output_crt)
        return

    mode_flags = {'--crt', '-c', '--xbank', '-x', '--list'}
    if not any(a in mode_flags for a in args_raw):
        if len(disk_args) == 1 and len(crt_args) == 1:
            # Inject --crt into our local copy only — never mutate sys.argv
            args_raw = ['--crt'] + list(args_raw)
            print("disk2easyflash: single-disk mode (auto-detected --crt)", file=sys.stderr)

    p = argparse.ArgumentParser(
        prog='disk2easyflash',
        description='*** DISK2EASYFLASH V1.00 ***  Convert C64 disk images to EasyFlash cartridges.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            'Examples:\n'
            '  %(prog)s --crt game.d64 game.crt\n'
            '  %(prog)s --crt game.d81 game.crt\n'
            '  %(prog)s --xbank --low game.d64 game.crt\n'
            '  %(prog)s --list game.d81\n'
            '  %(prog)s --crt --remove 3 --ignore 5 game.d64 game.crt\n'
            '  %(prog)s --multi pacman.d64 rambo.d81 out.crt\n'
        ),
    )

    build = p.add_mutually_exclusive_group(required=True)
    build.add_argument('--crt',   '-c', action='store_true',
                       help='Build an EasyFlash cartridge (.crt)')
    build.add_argument('--xbank', '-x', action='store_true',
                       help='Build an EasyFlash XBANK cartridge')
    build.add_argument('--list',  action='store_true',
                       help='List contents of disk image without building')

    bank = p.add_mutually_exclusive_group()
    bank.add_argument('--normal', action='store_true',
                      help='Use full 16 KiB banks (default)')
    bank.add_argument('--low',    action='store_true',
                      help='Use only lower 8 KiB banks ($8000)')
    bank.add_argument('--high',   action='store_true',
                      help='Use only upper 8 KiB banks ($A000, Ultimax)')

    p.add_argument('--nolisting', '-n', action='store_true',
                   help='Do not add the LOAD "$" listing')
    p.add_argument('--blocks-free', type=int, default=2, metavar='N',
                   help='Blocks-free count shown in listing (default: 2)')
    p.add_argument('--remove', '-r', type=int, action='append', default=[],
                   metavar='ID',
                   help='Remove entry #ID from listing and cartridge')
    p.add_argument('--ignore', '-i', type=int, action='append', default=[],
                   metavar='ID',
                   help='Keep entry #ID in listing but not in flash '
                        '(useful for savegame placeholders)')
    p.add_argument('--verbose', '-v', action='store_true',
                   help='Print file listing even in --crt/--xbank mode')

    p.add_argument('input',  help='Input .d64, .d81, or .m2i file (or directory containing .m2i)')
    p.add_argument('output', nargs='?', help='Output .crt file')

    args = p.parse_args(args_raw)

    if not args.list and args.output is None:
        p.error('output file is required for --crt and --xbank')

    # --- Determine bank mode ---
    if args.high:
        mode = 'hi'
    elif args.low:
        mode = 'lo'
    else:
        mode = 'nm'

    # --- Resolve input file ---
    input_path = args.input
    is_m2i     = False

    if os.path.isdir(input_path):
        found = next(
            (os.path.join(input_path, f)
             for f in os.listdir(input_path)
             if f.lower().endswith('.m2i')),
            None,
        )
        if found is None:
            sys.exit(f"No .m2i file found in directory: {input_path}")
        input_path = found
        is_m2i     = True
    else:
        is_m2i = input_path.lower().endswith('.m2i')

    # --- Parse disk image (D64, D81, or M2I) ---
    entries = _load_disk(input_path)

    # --- Apply --remove ---
    for remove_id in args.remove:
        num = 0
        done = False
        for e in entries[1:]:
            if e.type != '*':
                num += 1
                if num == remove_id:
                    e.type = '*'
                    done = True
                    break
        if not done:
            sys.exit(f"Cannot remove entry {remove_id}: no such entry")

    # --- Apply --ignore ---
    for ignore_id in args.ignore:
        num = 0
        done = False
        for e in entries[1:]:
            if e.type == 'p':
                num += 1
                if num == ignore_id:
                    e.type = 'q'
                    done = True
                    break
        if not done:
            sys.exit(f"Cannot ignore entry {ignore_id}: no such entry")

    # --- Build listing ---
    if not args.nolisting:
        listing = build_listing(entries, args.blocks_free)
        entries.append(listing)

    # --- Print listing (--list or --verbose) ---
    if args.list or args.verbose:
        hdr = entries[0]
        print(f'      | 0 "{hdr.name:<16}" {hdr.id} |')
        num = 0
        for idx, e in enumerate(entries[1:], 1):
            if e.type == '*':
                continue
            if args.list and not args.nolisting and idx == len(entries) - 1:
                break
            num += 1
            size   = (e.length + 253) // 254
            qname  = f'"{e.name}"'
            ftype  = 'DEL' if e.type == 'd' else 'PRG'
            note   = ', not in flash, only in listing' if e.type == 'q' else ''
            print(f'{num:4d}  | {size:<4d}  {qname:<18} {ftype} |  '
                  f'{e.length:5d} Bytes{note}')

        if not args.list and not args.nolisting and len(entries) > 1:
            last = entries[-1]
            print(f'      |       The Listing ("$")      |  {last.length:5d} Bytes')

    # --- Build output file ---
    if not args.list:
        basename = os.path.basename(input_path)
        with open(args.output, 'wb') as out:
            if args.crt:
                write_cart_header(out, CART_TYPE_EASYFLASH, 1, 0, basename)
                write_bank0_crt(out, mode)
                if mode == 'nm':
                    bundle(out, entries, 0x4000, 0x8000, 14, KAPI_NM, None, 1)
                elif mode == 'lo':
                    bundle(out, entries, 0x2000, 0x8000, 13, KAPI_LO, None, 1)
                else:  # hi
                    bundle(out, entries, 0x2000, 0xA000, 13, KAPI_HI, LAUNCHER_HI, 1)

            else:  # --xbank
                if mode == 'hi':
                    exrom, game = 1, 0
                elif mode == 'lo':
                    exrom, game = 0, 1
                else:
                    exrom, game = 0, 0
                write_cart_header(out, CART_TYPE_EASYFLASH_XBANK, exrom, game, basename)
                if mode == 'nm':
                    bundle(out, entries, 0x4000, 0x8000, 14, KAPI_NM, None, 0)
                elif mode == 'lo':
                    bundle(out, entries, 0x2000, 0x8000, 13, KAPI_LO, None, 0)
                else:  # hi
                    bundle(out, entries, 0x2000, 0xA000, 13, KAPI_HI, LAUNCHER_HI, 0)

        print(f"Written: {args.output}", file=sys.stderr)


if __name__ == '__main__':
    main()